function openCredits(){
    const mainBody = document.querySelector('.main-body');
    mainBody.classList.remove('menu-body');
    mainBody.classList.remove('home-body');
    mainBody.textContent = '';
    mainBody.classList.add('credit-body');
    const backgroundImg = document.createElement('a');
    const homeBodyImg = document.createElement('a');
    const menuImg1 = document.createElement('a');
    const menuImg2 = document.createElement('a');
    const menuImg3 = document.createElement('a');
    const menuImg4 = document.createElement('a');
    const menuImg5 = document.createElement('a');
    const menuImg6 = document.createElement('a');
    backgroundImg.setAttribute('href', '#');
    homeBodyImg.setAttribute('href', '#');
    menuImg1.setAttribute('href', '#');
    menuImg2.setAttribute('href', '#');
    menuImg3.setAttribute('href', '#');
    menuImg4.setAttribute('href', '#');
    menuImg5.setAttribute('href', '#');
    menuImg6.setAttribute('href', '#');
    const backgroundImgtext = document.createTextNode('Background Image (Unsplash)');
    const homeBodyImgtext = document.createTextNode('Home Image (Unsplash)');
    const menuImgtext1 = document.createTextNode('Menu Image 1 (Unsplash)');
    const menuImgtext2 = document.createTextNode('Menu Image 2 (Unsplash)');
    const menuImgtext3 = document.createTextNode('Menu Image 3 (Unsplash)');
    const menuImgtext4 = document.createTextNode('Menu Image 4 (Unsplash)');
    const menuImgtext5 = document.createTextNode('Menu Image 5 (Unsplash)');
    const menuImgtext6 = document.createTextNode('Menu Image 6 (Unsplash)');
    backgroundImg.appendChild(backgroundImgtext);
    homeBodyImg.appendChild(homeBodyImgtext);
    menuImg1.appendChild(menuImgtext1);
    menuImg2.appendChild(menuImgtext2);
    menuImg3.appendChild(menuImgtext3);
    menuImg4.appendChild(menuImgtext4);
    menuImg5.appendChild(menuImgtext5);
    menuImg6.appendChild(menuImgtext6);
    mainBody.appendChild(backgroundImg);
    mainBody.appendChild(homeBodyImg);
    mainBody.appendChild(menuImg1);
    mainBody.appendChild(menuImg2);
    mainBody.appendChild(menuImg3);
    mainBody.appendChild(menuImg4);
    mainBody.appendChild(menuImg5);
    mainBody.appendChild(menuImg6);
}
export default openCredits;